## Mushroom Poison detection with Artificial Neural Networks

### Introduction
Mushroom is one of the important ingredient in our food that has good nutrients. Most types of mushroom are poisonous (inedible), and because of its importance, we need to identify poisonous from eatable mushrooms.
We use Aritificial Neural Networks classify the posionnous mushrooms form the edible ones

### Problem Statement
The dataset includes descriptions of hypothetical samples corresponding to 23 species of gilled mushrooms in the Agaricus and Lepiota Family Mushroom drawn from The Audubon Society Field Guide to North American Mushrooms (1981). Each species is identified as definitely edible, definitely poisonous, or of unknown edibility and not recommended. This latter class was combined with the poisonous one. The Guide clearly states that there is no simple rule for determining the edibility of a mushroom; no rule like "leaflets three, let it be'' for Poisonous Oak and Ivy.

### Project Description : PEAS
Performance measure : Accuracy of detecting poison
Environment : Damp and moist environment which is ideal mushroom habitat
Sensors : Camera, moisture sensor, barometer
Agent type : Model based reflex agent

### Methodology
Artificial Neural Network

### Proposed solution
Using a camera to click pictures of the mushroom, identiy, classify and label images, and create dataset of said mushrooms.
Dataset is split into training and testing data, and Neural network is trained on the training data.
Testing Dataset reveals accuracy of final data.
Using this Neural Networks.

### Conclusion
Any given mushroom given that it is labelled properly, can be now classified and poisonous or edible by this dataset with 89.996 % accuracy.
Aritifical Neural networks is a great way to test the edibility of given mushrooms. But the accuracy is only 89.996 %. More accurate models can be used to improve the accuracy further.



In [ ]:
import numpy as np
import pandas as pd

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf

In [ ]:
df = pd.read_csv('mushrooms.csv')
df.head()

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0     p         x           s         n       t    p               f   
1     e         x           s         y       t    a               f   
2     e         b           s         w       t    l               f   
3     p         x           y         w       t    p               f   
4     e         x           s         g       f    n               f   

  gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0            c         n          k  ...                        s   
1            c         b          k  ...                        s   
2            c         b          n  ...                        s   
3            c         n          n  ...                        s   
4            w         b          k  ...                        s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

In [ ]:
df.describe()

class cap-shape cap-surface cap-color bruises  odor gill-attachment  \
count   8124      8124        8124      8124    8124  8124            8124   
unique     2         6           4        10       2     9               2   
top        e         x           y         n       f     n               f   
freq    4208      3656        3244      2284    4748  3528            7914   

       gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
count          8124      8124       8124  ...                     8124   
unique            2         2         12  ...                        4   
top               c         b          b  ...                        s   
freq           6812      5612       1728  ...                     4936   

       stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
count                    8124                   8124      8124       8124   
unique                      9                      9         1          4   
top                         w                      w         p          w   
freq                     4464                   4384      8124       7924   

       ring-number ring-type spore-print-color population habitat  
count         8124      8124              8124       8124    8124  
unique           3         5                 9          6       7  
top              o         p                 w          v       d  
freq          7488      3968              2388       4040    3148  

[4 rows x 23 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   class                     8124 non-null   object
 1   cap-shape                 8124 non-null   object
 2   cap-surface               8124 non-null   object
 3   cap-color                 8124 non-null   object
 4   bruises                   8124 non-null   object
 5   odor                      8124 non-null   object
 6   gill-attachment           8124 non-null   object
 7   gill-spacing              8124 non-null   object
 8   gill-size                 8124 non-null   object
 9   gill-color                8124 non-null   object
 10  stalk-shape               8124 non-null   object
 11  stalk-root                8124 non-null   object
 12  stalk-surface-above-ring  8124 non-null   object
 13  stalk-surface-below-ring  8124 non-null   object
 14  stalk-color-above-ring  

In [ ]:
for col in df.columns:
    print(col, " : ", df[col].unique())

class  :  ['p' 'e']
cap-shape  :  ['x' 'b' 's' 'f' 'k' 'c']
cap-surface  :  ['s' 'y' 'f' 'g']
cap-color  :  ['n' 'y' 'w' 'g' 'e' 'p' 'b' 'u' 'c' 'r']
bruises  :  ['t' 'f']
odor  :  ['p' 'a' 'l' 'n' 'f' 'c' 'y' 's' 'm']
gill-attachment  :  ['f' 'a']
gill-spacing  :  ['c' 'w']
gill-size  :  ['n' 'b']
gill-color  :  ['k' 'n' 'g' 'p' 'w' 'h' 'u' 'e' 'b' 'r' 'y' 'o']
stalk-shape  :  ['e' 't']
stalk-root  :  ['e' 'c' 'b' 'r' '?']
stalk-surface-above-ring  :  ['s' 'f' 'k' 'y']
stalk-surface-below-ring  :  ['s' 'f' 'y' 'k']
stalk-color-above-ring  :  ['w' 'g' 'p' 'n' 'b' 'e' 'o' 'c' 'y']
stalk-color-below-ring  :  ['w' 'p' 'g' 'b' 'n' 'e' 'y' 'o' 'c']
veil-type  :  ['p']
veil-color  :  ['w' 'n' 'o' 'y']
ring-number  :  ['o' 't' 'n']
ring-type  :  ['p' 'e' 'l' 'f' 'n']
spore-print-color  :  ['k' 'n' 'u' 'h' 'w' 'r' 'o' 'y' 'b']
population  :  ['s' 'n' 'a' 'v' 'y' 'c']
habitat  :  ['u' 'g' 'm' 'd' 'p' 'w' 'l']


In [ ]:
from sklearn.preprocessing import LabelEncoder
def label_encoding(c):
    le = LabelEncoder()
    df[c] = le.fit_transform(df[c])
    df[c].unique()
for col in df.columns:
    label_encoding(col)
df.head()

class  cap-shape  cap-surface  cap-color  bruises  odor  gill-attachment  \
0      1          5            2          4        1     6                1   
1      0          5            2          9        1     0                1   
2      0          0            2          8        1     3                1   
3      1          5            3          8        1     6                1   
4      0          5            2          3        0     5                1   

   gill-spacing  gill-size  gill-color  ...  stalk-surface-below-ring  \
0             0          1           4  ...                         2   
1             0          0           4  ...                         2   
2             0          0           5  ...                         2   
3             0          1           5  ...                         2   
4             1          0           4  ...                         2   

   stalk-color-above-ring  stalk-color-below-ring  veil-type  veil-color  \
0                       7                       7          0           2   
1                       7                       7          0           2   
2                       7                       7          0           2   
3                       7                       7          0           2   
4                       7                       7          0           2   

   ring-number  ring-type  spore-print-color  population  habitat  
0            1          4                  2           3        5  
1            1          4                  3           2        1  
2            1          4                  3           2        3  
3            1          4                  2           3        5  
4            1          0                  3           0        1  

[5 rows x 23 columns]

In [ ]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
X = df.iloc[:, 1:]
y = df.iloc[:, 0]

In [ ]:
bestfeatures = SelectKBest(score_func=chi2, k=2)
fit = bestfeatures.fit(X,y)

In [ ]:
dfscores = pd.DataFrame(fit.scores_)
dfcolumns = pd.DataFrame(X.columns)

In [ ]:
featureScores = pd.concat([dfcolumns,dfscores],axis=1)
featureScores.columns = ['Specs','Score']

In [ ]:
featureScores

Specs        Score
0                  cap-shape    17.508364
1                cap-surface   214.068544
2                  cap-color    11.511382
3                    bruises  1194.277352
4                       odor    75.910163
5            gill-attachment     3.505447
6               gill-spacing   826.795274
7                  gill-size  1636.606833
8                 gill-color  5957.764469
9                stalk-shape    36.594105
10                stalk-root  1186.029221
11  stalk-surface-above-ring   222.982400
12  stalk-surface-below-ring   206.648180
13    stalk-color-above-ring   119.792216
14    stalk-color-below-ring   109.789410
15                 veil-type          NaN
16                veil-color     5.126826
17               ring-number    25.646335
18                 ring-type  1950.610146
19         spore-print-color   379.132729
20                population   311.766736
21                   habitat   751.309489

In [ ]:
print(featureScores.nlargest(2,'Score'))

         Specs        Score
8   gill-color  5957.764469
18   ring-type  1950.610146


In [ ]:
X = bestfeatures.transform(X)

In [ ]:
X

array([[ 4,  4],
       [ 4,  4],
       [ 5,  4],
       ...,
       [ 5,  4],
       [ 0,  0],
       [11,  4]])

In [ ]:
y

0       1
1       0
2       0
3       1
4       0
       ..
8119    0
8120    0
8121    0
8122    1
8123    0
Name: class, Length: 8124, dtype: int64

In [ ]:
X = pd.DataFrame(X)
y = pd.DataFrame(y)

# Define a size for your train set
train_size = int(0.8 * len(X))

# Split your dataset
X_train = X[:train_size]
X_test = X[train_size:]

y_train = y[:train_size]
y_test = y[train_size:]

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
ann = tf.keras.models.Sequential()

## Adding the input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

## Adding the second hidden layer
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

## Adding the output layer
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

In [ ]:
ann.compile(optimizer= 'adam', loss= 'binary_crossentropy',metrics= ['accuracy'])

In [ ]:
ann.fit(X_test, y_test, batch_size = 32, epochs = 100)

Epoch 1/100
51/51 [==============================] - 1s 2ms/step - loss: 1.0767 - accuracy: 0.3120
Epoch 2/100
51/51 [==============================] - 0s 2ms/step - loss: 0.7169 - accuracy: 0.4289
Epoch 3/100
51/51 [==============================] - 0s 2ms/step - loss: 0.4596 - accuracy: 0.9754
Epoch 4/100
51/51 [==============================] - 0s 2ms/step - loss: 0.3419 - accuracy: 0.9760
Epoch 5/100
51/51 [==============================] - 0s 2ms/step - loss: 0.2642 - accuracy: 0.9766
Epoch 6/100
51/51 [==============================] - 0s 2ms/step - loss: 0.2051 - accuracy: 0.9785
Epoch 7/100
51/51 [==============================] - 0s 2ms/step - loss: 0.1622 - accuracy: 0.9785
Epoch 8/100
51/51 [==============================] - 0s 2ms/step - loss: 0.1329 - accuracy: 0.9785
Epoch 9/100
51/51 [==============================] - 0s 2ms/step - loss: 0.1129 - accuracy: 0.9785
Epoch 10/100
51/51 [==============================] - 0s 2ms/step - loss: 0.0990 - accuracy: 0.9785
Epoch 11/

In [ ]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.values.reshape(len(y_test),1)),1))

51/51 [==============================] - 0s 1ms/step
[[1 1]
 [1 1]
 [1 1]
 ...
 [0 0]
 [1 1]
 [0 0]]


In [ ]:
y_pred

array([[ True],
       [ True],
       [ True],
       ...,
       [False],
       [ True],
       [False]])

In [ ]:
y_test

class
6499      1
6500      1
6501      1
6502      1
6503      1
...     ...
8119      0
8120      0
8121      0
8122      1
8123      0

[1625 rows x 1 columns]

In [ ]:
def compute_confusion_matrix(true, pred):
  '''Computes a confusion matrix using numpy for two np.arrays
  true and pred.

  Results are identical (and similar in computation time) to:
    "from sklearn.metrics import confusion_matrix"

  However, this function avoids the dependency on sklearn.'''

  K = len(np.unique(true)) # Number of classes
  result = np.zeros((K, K))

  for i in range(len(true)):
    result[true[i]][pred[i]] += 1

  return result

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 507    0]
 [   0 1118]]


1.0